version: '3.8'

services:
  postgres:
    image: postgres:14.11
    container_name: postgres
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - '6380:6379'
    restart: 'always'